### ISSUE TITLE
Covariant `Mapping`s key type?

### ISSUE THREAD

**Issue by LeeeeT** [KotlinIsland/basedmypy#803]
### Describe the problem

Why is `Mapping`s key type made covariant? This is already discussed and showed to be unsafe in https://github.com/python/typing/pull/273. This contradicts type theory.

### Severity

annoying but i can live with it

**Comment by KotlinIsland** [comment]
see #62

it's covariant because it's safe enough, the only case in which it would be unsafe is if someone intentionally writes a `__getitem__`/`get` that stores the input value. and when you write one of these functions, you will get an error from basedmypy:

[playground](https://mypy-play.net/?mypy=basedmypy-latest&python=3.12&gist=6c61830aad15f007e12436befa8652b9)

thanks for looking into basedmypy, if you have any questions i'm happy to discuss. we also have a discord if your interested

**Comment by LeeeeT** [comment]
Do I understand this correctly? Every time someone tries to write a `__getitem__` / `get` mypy will produce an error (more like a warning) and if they are sure the usage is safe they can ignore the error in this case, right?

**Comment by KotlinIsland** [comment]
yes, that's correct. although it is most definitely an error (albeit with a lengthy note), we don't emit warnings yet

**Comment by LeeeeT** [comment]
Thanks for the explanation ❤️
